name: watchtower

services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: watchtower-freshrss
    volumes:
      - ${FRESH_RSS_DATA:-freshrss_data}:/config
    environment:
      TZ: ${FRESH_RSS_TIMEZONE}
      PUID: ${UID}
      PGID: ${GID}
